version: '3.3'

services:
  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./mongo_data:/data/db
  # rabbitmq:
  #   image: rabbitmq:3.10.6-management
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=cartMs
    ports: 
      - '5432:5432'

