services:
  CartsMs.cart.CartRepository:
    class: ../../../../../contexts/cartsMs/cart/infrastructure/typeORM/typeORMCartRepository
    arguments: ["@Shared.TypeORMClientFactory"]

  CartsMs.cart.CartFindById:
    class: ../../../../../contexts/cartsMs/cart/application/findById/cartFindById
    arguments: ["@CartsMs.cart.CartRepository"]

  CartsMs.cart.CartCreate:
    class: ../../../../../contexts/cartsMs/cart/application/create/cartCreate
    arguments: ["@CartsMs.cart.CartRepository"]
