services:
  Apps.CartsMs.controllers.CartsGetByIdController:
    class: ../../controllers/cartsGetByIdController
    arguments: ["@Shared.QueryBus", "@Shared.Logger"]

  Apps.CartsMs.controllers.CartsPostController:
    class: ../../controllers/cartsPostController
    arguments: ["@Shared.CommandBus", "@Shared.Logger"]

  Apps.CartsMs.controllers.CartsItemsGetAllController:
    class: ../../controllers/cartItemsGetAllController
    arguments: ["@CartsMs.cartItem.CartItemFindAll", "@Shared.Logger"]

  Apps.CartsMs.controllers.CartsItemsPostController:
    class: ../../controllers/cartItemsPostController
    arguments: ["@CartsMs.cartItem.CartItemCreate", "@Shared.Logger"]
