services:
  Apps.CartsMs.controllers.CartsGetByIdController:
    class: ../../controllers/cartsGetByIdController
    arguments: ["@CartsMs.cart.CartFindById"]

  Apps.CartsMs.controllers.CartsPostController:
    class: ../../controllers/cartsPostController
    arguments: ["@CartsMs.cart.CartCreate"]

  Apps.CartsMs.controllers.CartsItemsGetAllController:
    class: ../../controllers/cartItemsGetAllController
    arguments: ["@CartsMs.cartItem.CartItemFindAll"]

  Apps.CartsMs.controllers.CartsItemsPostController:
    class: ../../controllers/cartItemsPostController
    arguments: ["@CartsMs.cartItem.CartItemCreate"]
