services:
  Shared.Logger:
    class: ../../../../../contexts/shared/infrastructure/wistonLogger
    arguments: []

  Shared.TypeORMConfig:
    factory:
      class: ../../../../../contexts/cartsMs/shared/infrastructure/typeORM/typeORMConfigFactory
      method: "createConfig"

  Shared.TypeORMClientFactory:
    factory:
      class: ../../../../../contexts/shared/infrastructure/typeORM/typeORMClientFactory
      method: "createClient"
    arguments: ["@Shared.TypeORMConfig"]

  Shared.DomainEventMapping:
    class: ../../../../../contexts/shared/infrastructure/eventBus/domainEventMapping
    arguments: ["!tagged domainEventSubscriber"]

  Shared.DomainEventJSONDeserializer:
    class: ../../../../../contexts/shared/infrastructure/eventBus/domainEventJSONDeserializer
    arguments: ["@Shared.DomainEventMapping"]

  Shared.DomainEventJSONSerializer:
    class: ../../../../../contexts/shared/infrastructure/eventBus/domainEventJSONSerializer
    arguments: []

  Shared.RabbitMqConfig:
    factory:
      class: ../../../../../contexts/cartsMs/shared/infrastructure/rabbitMqConfigFactory
      method: "createConfig"
 
  Shared.RabbitMqConnection:
    class: ../../../../../contexts/shared/infrastructure/eventBus/rabbitMQ/rabbitMqConnection
    arguments: ["@Shared.RabbitMqConfig"]

  Shared.RabbitMQConfigurer:
    class: ../../../../../contexts/shared/infrastructure/eventBus/rabbitMQ/rabbitMqConfigurer
    arguments: ["@Shared.RabbitMqConnection"]

  Shared.EventBus:
    class: ../../../../../contexts/shared/infrastructure/eventBus/rabbitMQ/rabbitMqEventBus
    arguments:
      [
        "@Shared.Logger",
        "@Shared.RabbitMqConfig",
        "@Shared.RabbitMqConnection",
        "@Shared.DomainEventJSONSerializer",
      ]

  Shared.EventConsumers:
    class: ../../../../../contexts/shared/infrastructure/eventBus/rabbitMQ/rabbitMqConsumers
    arguments:
      [
        "@Shared.Logger",
        "@Shared.RabbitMqConnection",
        "@Shared.DomainEventJSONDeserializer",
        "!tagged domainEventSubscriber",
        "@Shared.RabbitMqConfig",
      ]

  Shared.QueryHandlersMapper:
    class: ../../../../../contexts/shared/infrastructure/queryBus/queryHandlersMapper
    arguments: ["!tagged queryHandler"]

  Shared.QueryBus:
    class: ../../../../../contexts/shared/infrastructure/queryBus/inMemoryQueryBus
    arguments: ["@Shared.QueryHandlersMapper"]

  Shared.CommandHandlersMapper:
    class: ../../../../../contexts/shared/infrastructure/commandBus/commandHandlersMapper
    arguments: ["!tagged commandHandler"]

  Shared.CommandBus:
    class: ../../../../../contexts/shared/infrastructure/commandBus/inMemoryCommandBus
    arguments: ["@Shared.CommandHandlersMapper"]
